# Generated by Django 4.2.6 on 2023-10-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('teamLevel', models.CharField(blank=True, choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('N/A', 'N/A')], max_length=200)),
                ('teamName', models.CharField(blank=True, choices=[('Name1', 'Name1'), ('Name2', 'Name2'), ('Name3', 'Name3'), ('Name4', 'Name4'), ('Name5', 'Name5'), ('Name6', 'Name6'), ('Name7', 'Name7'), ('N/A', 'N/A')], max_length=200)),
                ('phoneNum', models.CharField(max_length=200)),
            ],
        ),
    ]
